#Create Execute File
All: 
	gcc -o execute/Handle source/Sighandle.c
	gcc -o execute/Send source/Sigsend.c
	gcc -o execute/Alarm source/Sigalarm.c
	gcc -o execute/Block source/Sigblock.c
	gcc -o execute/Fibo source/Sigfibo.c
	
#Execute File
Execute:
	execute/Fibo

#Delete File 
Clean:
	rm execute/Handle
	rm execute/Send
	rm execute/Alarm
	rm execute/Block
	rm execute/Fibo

#Test Codes
#-------------------------------------------------------
#execute/Handle
#-------------------------------------------------------
#execute/Send
#-------------------------------------------------------
#execute/Alarms
#-------------------------------------------------------
#execute/Block
#-------------------------------------------------------
