#Create Execute File
All: 
	gcc -o execute/Fork source/Frok.c
	gcc -o execute/Exit source/Exit.c
	gcc -o execute/Atexit source/Atexit.c
	gcc -o execute/Wait source/Wait.c
	gcc -o execute/Wait2 source/WaitTargetProcess.c
	gcc -o execute/Zombie source/ZombiePro.c
	gcc -o execute/Execl source/Execl.c
	gcc -o execute/SimShell source/SimpleShell.c
	
#Execute File
Execute:
	execute/SimShell

#Delete File 
Clean:
	rm execute/Fork
	rm execute/Exit
	rm execute/Atexit
	rm execute/Wait
	rm execute/Wait2
	rm execute/Zombie
	rm execute/Execl
	rm execute/SimShell

#Test Codes
# execute/Fork
#-------------------------------------------------------
#execute/Exit
#-------------------------------------------------------
#execute/Atexit
#-------------------------------------------------------
#execute/Wait
#-------------------------------------------------------
#execute/Wait2
#-------------------------------------------------------
#execute/Zombie
#-------------------------------------------------------
#execute/Execl
