#Make execute File
execute/main: source/main.c
	gcc -o execute/Share source/main.c
Execute:
	execute/Share ./source/target.txt ./source/dest.txt
	cat source/dest.txt
#Delete File 
Clean:
	rm execute/Share